module.exports = {'entities': [{
  "name": "John Smith",
  "cpref": "189381",
  "registered_address": "AS Coopers Building 26 Reid Street Hamilton HM 11 Bermuda",
  "entity_type": "Individual",
  "open_matters": "21",
  "closed_matters": "5",
  "sort_name": "SMITH JOHN",
  "date_of_birth": "1/1/2016",
  "date_deceased": "1/2/2016",
  "domicile": "British Virgin Islands",
  "residence": "British Virgin Islands",
  "nationality": "Italian",
  "phone": "1-988-123-1234",
  "fax": "716-234-530",
  "city": "Burlington",
  "province": "New Jersey",
  "zip_code": "08016",
  "country": "USA", 
  "positions": [{
    "matter": "123456789",
    "client_number": "11794591",
    "company_type": "Exempted/IBC",
    "posn_desc": "Director",
    "client_name": "Jinmao (China) Investments Holdings Limited",
    "address": "100 yonge st Toronto Ontario L43 2CA",
    "preferred_name": "preferred name",
    "title": "CFO",
    "phone_number": '647888327',
    "email": 'codancanada@law.ca'
  },
  {
    "matter": "987654321",
    "client_number": "8646391",
    "company_type": "Exempted Limited Partnership - CIMA Registerd",
    "posn_desc": "General Partner",
    "client_name": "HHR Atlas Master, L.P.",
    "address": "157 goodwoord park M2R RCC"
    }
  ]
},
{
  "name": "John Smith",
  "cpref": "12831",
  "registered_address": "26 Reid Street Hamilton HM 11 Bermuda",
  "entity_type": "Individual",
  "open_matters": "21",
  "closed_matters": "5",
  "sort_name": "SMITH JOHN",
  "date_of_birth": "1/3/1900",
  "date_deceased": "1/5/2015",
  "domicile": "Mexico",
  "residence": "England",
  "nationality": "South African",
  "phone": "1-788-443-5534",
  "fax": "812-333-430",
  "city": "Hamptons",
  "province": "New York",
  "zip_code": "10791",
  "country": "USA",
  "positions": []
}, {
  "name": "John T. Smith",
  "cpref": "1242",
  "registered_address": "AS Coopers BUilding 26 Reid Street Hamilton HM 11 Bermuda",
  "entity_type": "Individual",
  "open_matters": "7",
  "closed_matters": "0",
  "sort_name": "SMITH T. JOHN",
  "date_of_birth": "1/12/1980",
  "date_deceased": "1/1/2011",
  "domicile": "Canada",
  "residence": "Caymans Islands",
  "nationality": "Canadian",
  "phone": "1-444-443-5534",
  "fax": "654-244-430",
  "city": "Hunstville",
  "province": "Alabama",
  "zip_code": "64151",
  "country": "USA",
  "positions": []

}, {
  "name": "John Smithers",
  "cpref": "1231",
  "registered_address": "181 University Ave Toronto Ontario Canada",
  "entity_type": "Individual",
  "open_matters": "0",
  "closed_matters": "0",
  "sort_name": "SMITHERS JOHN",
  "date_of_birth": "1/10/1923",
  "date_deceased": "1/12/2012",
  "domicile": "Ireland",
  "residence": "South Africa",
  "nationality": "Italian",
  "phone": "1-788-443-831",
  "fax": "812-244-432",
  "city": "Ontario",
  "province": "Toronto",
  "zip_code": "M4C 2G8",
  "country": "Canada",
  "positions": []
}, {
  "name": "John SMithy Ltd",
  "cpref": "102",
  "registered_address": "New York United States",
  "entity_type": "Company",
  "open_matters": "0",
  "closed_matters": "12",
  "sort_name": "SMITHTY JOHN",
  "date_of_birth": "12/12/1950",
  "date_deceased": "12/12/2015",
  "domicile": "Morocco",
  "residence": "Egypt",
  "nationality": "Senegalese",
  "phone": "1-788-932-5534",
  "fax": "888-244-430",
  "city": "Lyon",
  "province": "ile de france",
  "zip_code": "213A",
  "country": "France",
  "positions": []
}
]};
